# Generated by Django 5.1.1 on 2024-09-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desconto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='formas_pagamento',
            options={'managed': False, 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='pagamentos',
            options={'managed': False, 'verbose_name': 'Pedido Pagamento', 'verbose_name_plural': 'Pedidos Pagamentos'},
        ),
    ]
