# Generated by Django 5.1.1 on 2024-09-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_desconto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'managed': False, 'verbose_name': 'Combo', 'verbose_name_plural': 'Combos'},
        ),
        migrations.AlterModelOptions(
            name='fluxoprodutoreceita',
            options={'managed': False, 'verbose_name': 'Fluxo Produto Receita', 'verbose_name_plural': 'Fluxo Produtos Receitas'},
        ),
        migrations.AlterModelOptions(
            name='movimento',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table=None,
        ),
    ]
