# Generated by Django 5.1.1 on 2024-09-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_combo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'managed': False, 'verbose_name': 'pedidos', 'verbose_name_plural': 'movimento'},
        ),
    ]
