# Generated by Django 5.1.1 on 2024-09-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedidos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itens',
            options={'managed': False, 'verbose_name': 'itens', 'verbose_name_plural': 'movimento_itens'},
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table='pedidos',
        ),
    ]
