# Generated by Django 5.1.1 on 2024-09-17 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=30)),
                ('classe', models.CharField(max_length=30)),
                ('loja', models.IntegerField()),
            ],
            options={
                'ordering': ['grupo'],
            },
        ),
        migrations.CreateModel(
            name='Tamanhos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('loja', models.IntegerField()),
                ('tamanho', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['tamanho'],
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('loja', models.IntegerField()),
                ('familia', models.CharField(max_length=20)),
                ('classe', models.CharField(max_length=30)),
                ('unidade_consumo', models.CharField(max_length=3)),
                ('classe_aquisicao', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50)),
                ('custo_real', models.FloatField()),
                ('icms_aliquota', models.FloatField()),
                ('ncm', models.CharField(max_length=15)),
                ('cfop_saida_est', models.CharField(max_length=10)),
                ('status_produto', models.CharField(max_length=20)),
                ('grupo', models.ForeignKey(db_column='grupo', on_delete=django.db.models.deletion.CASCADE, to='produto.grupos')),
                ('tamanho', models.ForeignKey(db_column='tamanho', on_delete=django.db.models.deletion.CASCADE, to='produto.tamanhos')),
            ],
            options={
                'verbose_name': 'produtos',
                'verbose_name_plural': 'produtos',
                'db_table': 'produtos',
                'ordering': ['grupo', 'tipo', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=1)),
                ('qtd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidade', models.CharField(max_length=3)),
                ('custo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('retirado', models.BooleanField(default=False)),
                ('adicionado', models.BooleanField(default=False)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_produto', related_query_name='receita_ingrediente', to='produto.produtos')),
                ('produto', models.ForeignKey(db_column='produto', on_delete=django.db.models.deletion.CASCADE, to='produto.produtos')),
            ],
            options={
                'verbose_name': 'produtos_receitas',
                'db_table': 'produtos_receitas',
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('loja', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('grupo', models.ForeignKey(db_column='grupo', on_delete=django.db.models.deletion.CASCADE, to='produto.grupos')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.AddField(
            model_name='tamanhos',
            name='tipo',
            field=models.ForeignKey(db_column='grupo', on_delete=django.db.models.deletion.CASCADE, to='produto.tipos'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='tipo',
            field=models.ForeignKey(db_column='tipo', on_delete=django.db.models.deletion.CASCADE, to='produto.tipos'),
        ),
    ]
