# Generated by Django 5.1.1 on 2024-09-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupos',
            options={'managed': False, 'ordering': ['grupo']},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'managed': False, 'ordering': ['grupo', 'tipo', 'descricao'], 'verbose_name': 'produtos', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterModelOptions(
            name='receitas',
            options={'managed': False, 'verbose_name': 'produtos_receitas'},
        ),
        migrations.AlterModelOptions(
            name='tamanhos',
            options={'managed': False, 'ordering': ['tamanho']},
        ),
    ]
