# Generated by Django 5.1.1 on 2024-09-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_grupos_options_alter_produtos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grupos',
            table='produto_grupos',
        ),
        migrations.AlterModelTable(
            name='tamanhos',
            table='produto_tamanhos',
        ),
    ]
